import type { RepoLanguageConfig } from '@/types/repo/editor.types';

export const SUPPORTED_LANGUAGES = {
  SPRING_BOOT: 'spring-boot',
  REACT: 'react',
  FASTAPI: 'fastapi',
} as const;

export const LANGUAGE_CONFIGS: Record<string, RepoLanguageConfig> = {
  [SUPPORTED_LANGUAGES.SPRING_BOOT]: {
    language: 'spring-boot',
    id: 'java',
    monacoLanguage: 'java',
    fileExtensions: [
      '.java',
      '.xml',
      '.properties',
      '.yaml',
      '.yml',
      '.gradle',
      '.gradle.kts',
      '.sql',
      '.jsp',
      '.jspx',
      '.ftl',
      '.vm',
      '.groovy',
      '.kt',
      '.kts',
      '.conf',
      '.toml',
    ],
    defaultTheme: 'vs-dark',
    snippets: ['sysout', 'psvm', 'fori'],
  },
  [SUPPORTED_LANGUAGES.REACT]: {
    language: 'react',
    id: 'typescript',
    monacoLanguage: 'typescript',
    fileExtensions: [
      '.ts',
      '.tsx',
      '.js',
      '.jsx',
      '.json',
      '.css',
      '.scss',
      '.sass',
      '.less',
      '.stylus',
      '.postcss',
      '.vue',
      '.svelte',
      '.mjs',
      '.cjs',
      '.d.ts',
      '.mdx',
      '.html',
      '.htm',
      '.env',
      '.env.local',
      '.env.development',
      '.env.production',
    ],
    defaultTheme: 'vs-dark',
    snippets: ['rfc', 'useState', 'useEffect'],
  },
  [SUPPORTED_LANGUAGES.FASTAPI]: {
    language: 'fastapi',
    id: 'python',
    monacoLanguage: 'python',
    fileExtensions: [
      '.py',
      '.pyi',
      '.pyx',
      '.requirements.txt',
      '.pyc',
      '.pyo',
      '.pyw',
      '.ipynb',
      '.toml',
      '.cfg',
      '.ini',
      '.txt',
      '.lock',
      '.pipfile',
      '.dockerfile',
      '.dockerignore',
      '.env',
      '.jinja',
      '.jinja2',
      '.j2',
      '.iml',
      '.http',
    ],
    defaultTheme: 'vs-dark',
    snippets: ['def', 'class', 'if', 'for'],
  },
};
