#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 브랜치명에서 DP-숫자 패턴 확인
branch=$(git rev-parse --abbrev-ref HEAD)
if echo "$branch" | grep -q "DP-[0-9]\+"; then
  case "$(uname -s)" in
    CYGWIN*|MINGW*|MSYS*)
      # Windows
      npx --yes jira-prepare-commit-msg $1
      ;;
    *)
      # macOS/Linux
      # TTY 사용 가능한지 확인하고, 가능하면 사용
      if [ -t 0 ] && [ -c /dev/tty ]; then
        exec < /dev/tty && npx --yes jira-prepare-commit-msg $1
      else
        # TTY 사용 불가능한 환경에서는 직접 실행
        npx --yes jira-prepare-commit-msg $1
      fi
      ;;
  esac
fi