name: Close Jira Issue when GitHub Issue is closed

on:
  issues:
    types: [closed]

jobs:
  close-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Jira 로그인
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Jira 이슈 완료 처리 (상태 전환)
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ github.event.issue.title }}
          transition: Done
